### ISSUE TITLE
why does memmap2::Mmap::map need to be unsafe?

### ISSUE THREAD

**Issue by dev-ardi** [RazrFalcon/memmap2-rs#101]
Most other ffi wrappers provide a safe interface. Why is this unsafe?

**Comment by dev-ardi** [comment]
I'm not talking about mmap wrappers, I'm talking about general libc wrappers.

This makes sense, is that in the docs? Did I miss it?

**Comment by RazrFalcon** [comment]
https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html#safety ?

**Comment by dev-ardi** [comment]
Ah that's great. It would be nice to add a link to that section in all unsafe APIs.
