### ISSUE TITLE
Composite memory maps currently impossible

### ISSUE THREAD

**Issue by mthom** [RazrFalcon/memmap2-rs#103]
I want to create a thread-local memory map (could be file-based or anonymous, I'd prefer anonymous) in each of N threads where the first M bytes of each thread-local mapping are mapped to the same file (which is itself mapped into memory). I know this allocation scheme is possible using plain `mmap` in Linux but I can't find a way to do it in `memmap2-rs`. That is, there is no way to map the buffer of a `MMapMut` into the buffer of another `MMap*` struct.

Am I wrong to believe this or is it truly impossible under the current API?

**Comment by adamreichold** [comment]
Can you please illustrate the C or at least plain `mmap` call sequence you would use?

From your description, I wonder why you just don't pass the byte slice itself to the other threads? And what kind of synchronization exists between them as multiple threads writing into the same mapping without synchronization is likely to imply a data race.

**Comment by adamreichold** [comment]
(It is also not clear to me what "thread-local memory map" means here as a memory mapping is by design process-wide as all threads share a single address space in which all memory maps are contained.)

**Comment by mthom** [comment]
Here's some code from the `slice_deque` crate that calls to the POSIX mmap:
```
let ptr = mmap(
            ptr::null_mut(),
            size,
            PROT_READ | PROT_WRITE,
            MAP_SHARED,
            fd,
            0,
        );
        if ptr == MAP_FAILED {
            print_error("@first: mmap failed");
            if close(fd) == -1 {
                print_error("@first: close failed");
            }
            return Err(AllocError::Oom);
        }

        let ptr2 = mmap(
            (ptr as *mut u8).offset(half_size as isize) as *mut c_void,
            half_size,
            PROT_READ | PROT_WRITE,
            MAP_SHARED | MAP_FIXED,
            fd,
            0,
        );
```
In `ptr2`, a second map is created by offsetting into the first map at `ptr`.

The reason for this is because I'm implementing a concurrent Prolog runtime in Rust with a consolidated heap. The first section of the heap (the memory map shared among all threads) is the atom table. The second section that comes immediately after it is the Prolog heap. Cells in the Prolog heap compose Prolog terms. Prolog terms can point down into the atom table. 

> From your description, I wonder why you just don't pass the byte slice itself to the other threads? 
For the sake of sharing the atom table mapping across threads and because of the Prolog VM design, it's most convenient to map the atom table contiguously in memory next to the thread-local Prolog heap. In particular, converting atoms to strings (lists of characters) is very efficient.

> (It is also not clear to me what "thread-local memory map" means here as a memory mapping is by design process-wide as all threads share a single address space in which all memory maps are contained.)
By that I mean that every VM thread will have its own `MMapMut` object that is local to that thread but that contains the atom table `MMap*` as a sub-map.

> And what kind of synchronization exists between them as multiple threads writing into the same mapping without synchronization is likely to imply a data race.
Absolutely, I plan to use RCU to manage that. But that's outside the scope of the `memmap-rs` library.

**Comment by mthom** [comment]
A `Lis` of characters can live in either the heap or the atom table. I don't want to have implement logic to determine whether it points into another heap location or into a separate atom table. It would severely complicate the runtime. And slow it down considerably, too.

**Comment by mthom** [comment]
If PRs are welcome for this, I'll try to implement `MAP_FIXED`. I need it to work on Windows too, so I'll be looking at that as well.

**Comment by mthom** [comment]
You are right, fixing memory maps is not possible in Windows. Closing this issue.
