### ISSUE TITLE
mmap'd anon pages fail in io_uring  IOSQE_BUFFER_SELECT usage

### ISSUE THREAD

**Issue by rrichardson** [RazrFalcon/memmap2-rs#104]
This is half a question, and half a bug report.

I have some test code that goes through several permutations of how to execute io_uring operations using various buffer strategies.  One strategy (my default, actually) kept failing with  -14 Bad Address / EFAULT errors. 

Tracking it down, it seemed to be only buffers from mmap'd pages that cause this,  digging further.. it was only mmap'd pages that had been allocated via memmap2(?)

```rust
    let adjusted_buf_size = size.checked_next_power_of_two().unwrap();
    let buf_layout = std::alloc::Layout::from_size_align(adjusted_buf_size, PAGE_ALIGN).unwrap();
    let buf_total = buf_layout.size().checked_mul(count).unwrap();

    let buf_ptr = if OLD_SKOOL {
        let buf_ptr = libc::mmap(
            std::ptr::null_mut(),
            buf_total,
            libc::PROT_WRITE | libc::PROT_READ,
            libc::MAP_ANON | libc::MAP_POPULATE | libc::MAP_PRIVATE,
            -1,
            0,
        );
        if buf_ptr == libc::MAP_FAILED {
            panic!("mmap failed");
        }
        buf_ptr.cast()
    } else {
        let mut opts = MmapOptions::new();
        let mut buf = opts.populate().len(buf_total).map_anon().unwrap();
        buf.as_mut_ptr()
    };
    // belt and suspenders
    std::ptr::write_bytes(buf_ptr, 0, buf_total);
``` 
    
When OLD_SKOOL is true, then everything works as planned.  If OLD_SKOOL is false, then all read via io_uring fail with the -14 Bad Address. 

Before the registration of each buffer, I assert that they are aligned to 4096.   I am baffled as to what the difference in approaches might be.

**Comment by adamreichold** [comment]
Could you share what the issue was? Maybe other people will run into it as well and could then quickly find the solution here.

**Comment by rrichardson** [comment]
It's rather embarrassing really.   `buf` goes out of scope at the end of the `else` clause.  There is a `drop` impld for MmapInner which `munmap`'s the region that was just `mmap`'d .  RIAA for the loss.  

It makes sense that something should control the lifetime of the mmap'd region,  but it was a tiny bit of a surprise because I looked for a drop impl'd on MmapMut, and there was none.  It is impl'd on the private type `MmapInner` that is owned by MmapMut.  It's a bit of a sharp edge, but I should have known.
