### ISSUE TITLE
no-std support

### ISSUE THREAD

**Issue by Krantz-XRF** [RazrFalcon/memmap2-rs#11]
I wonder whether or not we can make this crate `no-std`?

AFAIC, at least the anonymous mapping API (`map_anon`) should not depend on any `std` features.

This might not help a lot on UNIX since it depends on `libc` whatsoever. But on Windows, making this crate `no-std` should reduce link targets and/or executable size.

If you find this change proper, I could start working on this and (hopefully) make a PR soon.

**Comment by Krantz-XRF** [comment]
After some investigating, I found out that `std::io::Error` is extensively used, and hard to be replaced by something available in `core` which preserves backward compatibility of the API interface. I guess it is not possible without changing (or adding) the API interface.

**Comment by RazrFalcon** [comment]
Yes, `std::fs` is required.
