### ISSUE TITLE
Support for `MS_INVALIDATE`?

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [RazrFalcon/memmap2-rs#111]
First, thanks for maintaining this crate.  It's very useful!

I'm wondering if there's a reason some kind of support for `MS_INVALIDATE` isn't exposed for `.flush[_async]()` and `.flush[_async]_range()`?  If there isn't and you'd like a PR, I'd be happy to send one.

Tho I wanted to ask if you have any thoughts on what the user-facing API should look like for that?  I was thinking of adding four new functions, `.flush[_async]_and_invalidate()` and `.flush[_async]_range_and_invalidate()`.

I suppose some field could be added to `MmapMut` during construction as well, but `MS_INVALIDATE` seems like a decision the caller would make at flush time and not necessarily know *a priori*.

Thoughts?

**Comment by adamreichold** [comment]
I guess this would either be more methods or we take the time to consolidate the existing methods into a builder-like pattern, e.g.

```rust
map.flush().async().range(10, 20).invalidate().sync();
```

or at least as function parameters, e.g.

```
fn flush(&self, async: bool, invalidate: bool) -> Result<()>;
```

That said, what is your use case for this? It seems, `MS_INVALIDATE` is actually a no-op since the unified page cache replaced the buffer cache, c.f. https://stackoverflow.com/questions/60547532/whats-the-exact-meaning-of-the-flag-ms-invalidate-in-msync

**Comment by RazrFalcon** [comment]
>I'm wondering if there's a reason some kind of support for MS_INVALIDATE isn't exposed

In most cases because no one asked for it. It's that simple. `memmap2` is intentionally bare-bone.

**Comment by RazrFalcon** [comment]
@adamreichold 

>builder-like pattern

The problem with the builder pattern is that it's absurdly verbose, implementation-wise, most of the time. If only Rust had named arguments like Swift... One could only wish. 

Therefore `fn flush(&self, async: bool, invalidate: bool)` is our only choice.

**Comment by adamreichold** [comment]
> The problem with the builder pattern is that it's absurdly verbose, implementation-wise, most of the time. If only Rust had named arguments like Swift... One could only wish.

I think the closest would be a single structure for the arguments, e.g.

```rust
#[derive(Default)]
struct FlushParams {
  async: bool,
  invalidate: bool,
  range: Option<Range<usize>>,
}

fn flush(&self, params: FlushParams) -> Result<()>;

map.flush(FlushParams { invalidate: true, ..Default::default() })?;
```

But then again, I think we should really figure out the underlying use case here because making the API more complex in any way to support what is essentially a no-op on all but the most historic[^1] kernels seems ill-advised.

[^1]: Page and buffer cache were unified in 1999, c.f. https://lwn.net/Articles/712467/

**Comment by RazrFalcon** [comment]
Yes, I was commenting mostly on the API. As for `MS_INVALIDATE` - I have no idea. If it's pointless - then we should ignore it.

**Comment by eeeebbbbrrrr** [comment]
> what is essentially a no-op on all but the most historic[1](https://github.com/RazrFalcon/memmap2-rs/issues/111#user-content-fn-1-fb4ecb0e2e3a5ed0292bbaf88ebf985f) kernels seems ill-advised.

huh.  Well, I did not know this.

I did spend some time searching github repos for code that uses `MS_INVALIDATE` and I thought it was weird that all I found were definitions of the flag, not actual uses to `msync`.  Its man page really needs to be updated if this is true.

`MS_INVALIDATE` came to my attention b/c I'm trying to track down some cross-process concurrency bug that I suspect is related to a mmap'd file they share.  That said, I hacked this crate locally to add the flag and it didn't magically fix my problem anyways.

I'll just close this issue then.  Looks like it's unnecessary and there's point in redesigning the flush api for fun.

Thanks for y'alls input!

**Comment by adamreichold** [comment]
> MS_INVALIDATE came to my attention b/c I'm trying to track down some cross-process concurrency bug that I suspect is related to a mmap'd file they share. That said, I hacked this crate locally to add the flag and it didn't magically fix my problem anyways.

Note that even file-backed pages in the page cache are just that, pages of memory. This implies that cross-process synchronization between multiple processes mapping a file should be possible using (address-free) atomic operations.

**Comment by eeeebbbbrrrr** [comment]
> This implies that cross-process synchronization between multiple processes mapping a file should be possible using (address-free) atomic operations.

In fact, @workingjubilee and I were just discussing this very thing offline.  And is likely where I'll be headed next.
