### ISSUE TITLE
Implementing DerefMut for Mmap?

### ISSUE THREAD

**Issue by jrcichra** [RazrFalcon/memmap2-rs#113]
Hi, I'm a rust noobie and was trying to build a `HashMap<String,Mmap>`, as a way to have a dynamic global store of files and their corresponding memory maps.

I previously did `HashMap<String,File>` and was able to call `.get_mut(&path)`, presumably since std::io::File implements `Deref` & `DerefMut`.

I was trying memory mapped I/O to see if it gives me any performance advantage over `File` + `Seek` + `.read()/.write()` for my use case.

Would it be possible / is it reasonable to implement `DerefMut` on `Mmap`? Or is there some other method I can use for holding a RW `Mmap` inside a `HashMap`?

Thanks!

**Comment by RazrFalcon** [comment]
I guess only via [Mmap::make_mut](https://docs.rs/memmap2/latest/memmap2/struct.Mmap.html#method.make_mut). `File` doesn't have a mutable variant, unlike `mmap`.

**Comment by adamreichold** [comment]
Meaning `MmapMut` already implements `DerefMut`, c.f. <https://docs.rs/memmap2/latest/memmap2/struct.MmapMut.html#impl-DerefMut-for-MmapMut>

**Comment by jrcichra** [comment]
Oh perfect, I missed there was a `MmapMut`. Thanks!
