### ISSUE TITLE
New crates.io owners?

### ISSUE THREAD

**Issue by smoelius** [RazrFalcon/memmap2-rs#126]
Sorry for what is likely noise, but I noticed this package has two new crates.io owners (@tbu- and @de-vri-es).

I can't find any commits from them, currently.

So can I just confirm their additions were intentional?

**Comment by tbu-** [comment]
https://github.com/RazrFalcon/memmap2-rs/issues/124#issuecomment-2423731486.

**Comment by smoelius** [comment]
Thanks, @tbu-!
