### ISSUE TITLE
qeustion for two programs sharememory

### ISSUE THREAD

**Issue by dxh-sc** [RazrFalcon/memmap2-rs#135]
Hi,
Does this library support shared memory between two programs? 
One program writes data to the shared memory, while the other program reads data from the shared memory

**Comment by adamreichold** [comment]
Yes, it does via both programs mapping the same file. Note that you need to take care of synchronization yourself though, e.g. use `MmapRaw` and work using address-free atomics like `AtomicUsize`.

There are other crates which specifically target the shared memory use case and help with synchronization, for example `ipc-channel` for a really high-level abstraction or `shared_memory` for something more low-level.

**Comment by dxh-sc** [comment]
Thank for your answer
