### ISSUE TITLE
Documentation of safety invariants

### ISSUE THREAD

**Issue by oilaba** [RazrFalcon/memmap2-rs#16]
[`MmapMut::map_mut`](https://docs.rs/memmap2/0.2.1/memmap2/struct.MmapMut.html#method.map_mut) is an `unsafe` function, but there is not any documentation about why it is `unsafe` and which invariants the user have to hold.

**Comment by RazrFalcon** [comment]
#13 ?

**Comment by RazrFalcon** [comment]
https://docs.rs/memmap2/0.2.1/memmap2/struct.MmapMut.html#safety
