### ISSUE TITLE
Supporting zero-size Mmap?

### ISSUE THREAD

**Issue by SimonSapin** [RazrFalcon/memmap2-rs#23]
This test shows that mapping an empty file returns an error:

https://github.com/RazrFalcon/memmap2-rs/blob/27ece7685bfc4fe9909c396a651dc52306393a22/src/lib.rs#L978-L992

I assume this is because the underlying OS APIs do not support creating a zero-size mapping but it is unsatisfying, since in some cases it forces callers to handle that special case. What do you think of having the `Mmap` and `MmapMut` structs handle this case by not creating an actual mapping but not erroring when the length is zero, and instead have `Deref` return `&[]`?

**Comment by RazrFalcon** [comment]
I'm not the one who wrote this code, so I'm not sure. I guess this is a Unix limitation. From `mmap(2)`:

> The length argument specifies the length of the mapping (which must be greater than 0).

Overall, yes I think we can allow it.

**Comment by SimonSapin** [comment]
There’s more discussion of this here: https://github.com/danburkert/memmap-rs/issues/72

The idea of creating a *mapping* of always at least one memory page even if `Deref` ends up slicing it to zero size seems promising.
