### ISSUE TITLE
Support for async_std types?

### ISSUE THREAD

**Issue by gabrik** [RazrFalcon/memmap2-rs#24]
First, thank you for keeping alive this very useful crate.

I was wondering if there is any plan to support `async_std` types.
Especially in the `MmapOptions`.

As mentioned in the doc [https://docs.rs/async-std/1.10.0/async_std/fs/index.html](https://docs.rs/async-std/1.10.0/async_std/fs/index.html) those types are just the async version of the ones in the standard library, so I guess it should be quite easy.

Thanks

**Comment by RazrFalcon** [comment]
Only if someone will send a patch.

**Comment by gabrik** [comment]
Sounds reasonable, do you would like to have the `async_std` support as a feature? 
I think it would be better and in this way only people using `async_std` would activate it.

**Comment by RazrFalcon** [comment]
Fixed by #31
