### ISSUE TITLE
Support options for reducing page faults

### ISSUE THREAD

**Issue by FlorianUekermann** [RazrFalcon/memmap2-rs#3]
Having some options to reduce page faults would be great. On linux the `MAP_HUGETLB` and `MAP_POPULATE` options would be the most interesting imo.

**Comment by RazrFalcon** [comment]
Patches are welcome.

**Comment by adamreichold** [comment]
@RazrFalcon Concerning patches and the cross-platform target of this crate, would it be alright in your opinion to add an option like `readahead` to `MmapOptions` that maps to `MAP_POPULATE` on Linux but is a no-op on Windows? Or would you prefer a more complex implementation based on `posix_madvise` for better portability on non-Linux Unix platforms?

(Large pages seem to be available on both platforms even though the Windows variants seems to required more privileges.)

**Comment by RazrFalcon** [comment]
Yes, I think we could use no-op on Windows. `MmapOptions::stack()` already does this. Just note this in the docs.
