### ISSUE TITLE
Support std::io::{Read, Write, Seek}

### ISSUE THREAD

**Issue by ikrivosheev** [RazrFalcon/memmap2-rs#33]
Hello! Thank you for very useful crate!

Before Rust I wrote in python. Python has its implementation for [mmap](https://docs.python.org/3/library/mmap.html). In python I can work with **mmap** like with **File**
I propose to implement traits `std::io::{Read, Write, Seek}`. If nobody don't mind, I'm ready to create PR.

**Comment by adamreichold** [comment]
A memory map provides access to a byte slice `&[u8]` resp. `&mut [u8]` which implements [`Read`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#impl-Read-2) and [`Write`](https://doc.rust-lang.org/stable/std/io/trait.Write.html#impl-Write-6). If you need `Seek`, you'll just need to wrap the slice into a [`Cursor`](https://doc.rust-lang.org/stable/std/io/trait.Seek.html#impl-Seek-6). So `Cursor<MmapMut>` should already fulfil the requirement of using a memory map like a file?

**Comment by RazrFalcon** [comment]
Yes, as mentioned about, it should work out of the box.

**Comment by ikrivosheev** [comment]
@RazrFalcon @adamreichold, thank for the answer! I got it and it works!
