### ISSUE TITLE
Detaching from parent fork

### ISSUE THREAD

**Issue by nyurik** [RazrFalcon/memmap2-rs#39]
To my knowledge, github doesn't support searching if a project is a fork. Would it make sense to disable the `forked from` (it might require an email to github support, as there is no settings AFAIK)?  Seems like this project is much more alive than the parent (thx!!!)

**Comment by RazrFalcon** [comment]
Hmm... I didn't knew that.
On the other hand, I do not plan bothering github support for this. It's fine as it is.
