### ISSUE TITLE
Supporting madvise(...)

### ISSUE THREAD

**Issue by nyurik** [RazrFalcon/memmap2-rs#40]
Related (unsolved) discussion: https://github.com/danburkert/memmap-rs/issues/68

Would it be possible to support setting linux hints, similar to how this C++ code was modified  - https://github.com/osmcode/libosmium/pull/292/files

Or are there some issues with wrapping this kind of tech?  Thanks!

**Comment by RazrFalcon** [comment]
If someone is willing to implement this - sure.
