### ISSUE TITLE
panic on mismatched size?

### ISSUE THREAD

**Issue by zkat** [RazrFalcon/memmap2-rs#45]
Hi, I got this bug report: https://github.com/zkat/cacache-rs/issues/32

It seems to be a regression from `memmap` and I'm not really sure what's going on.

**Comment by adamreichold** [comment]
@zkat Could you elaborate on how mmap is used by cacache. Looking at the linked issue, the `Write` impl looks suspicious, i.e.
```rust
mmap.copy_from_slice(buf);
```
can only work if the mapped region has exactly the length of `buf`. Shouldn't there be some kind of cursor involved when implementing `Write`?

**Comment by zkat** [comment]
from reading the docs, it looks like it? I'm just surprised it never panicked like this before. 🤔

**Comment by adamreichold** [comment]
> from reading the docs, it looks like it? I'm just surprised it never panicked like this before. thinking

One thing I could image is that the mmap call in
```rust
let mmap = if let Some(size) = size {
    if size <= MAX_MMAP_SIZE {
        unsafe { MmapMut::map_mut(tmpfile.as_file()).ok() }
    } else {
        None
    }
} else {
    None
};
```
was silently failing in the past (i.e. `mmap == None` even though the file size was below `MAX_MMAP_SIZE`) and updating the dependency exposed the code path which was never taken before?

Alternatively, writes did happen in a single call in the past and so the lengths did match but that happened "by accident" in the above layers and some other change made this happen in smaller chunks now?

**Comment by zkat** [comment]
ah interesting. I guess it's a bug on my end. I'm already working on fixing it. Thanks so much, and sorry for the bother!
