### ISSUE TITLE
`map_anon()` can unsoundly create overlarge slices in safe code

### ISSUE THREAD

**Issue by LegionMammal978** [RazrFalcon/memmap2-rs#48]
On `i686-unknown-linux-gnu`, `mmap()` with `MAP_ANONYMOUS` is able to serve requests of 0x80000000 or more bytes. `MmapMut::map_anon()` and `<MmapMut as Deref>::deref()` can create a slice of this length in safe code:
```rust
/*
[dependencies]
memmap2 = "=0.5.4"

cargo run --target i686-unknown-linux-gnu
*/

use memmap2::MmapMut;

fn main() {
    let map: MmapMut = MmapMut::map_anon(0x80000000).unwrap();
    let slice: &[u8] = &*map;
    println!("{:#x}", slice.len()); // 0x80000000
}
```
However, `<MmapMut as Deref>::deref()` uses [`std::slice::from_raw_parts()`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html), which has this safety precondition:

> Behavior is undefined if any of the following conditions are violated: [...]
> - The total size `len * mem::size_of::<T>()` of the slice must be no larger than `isize::MAX`. See the safety documentation of [`pointer::offset`](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset).

Since `isize::MAX == 0x7fffffff` on `i686-unknown-linux-gnu` and other 32-bit targets, it is undefined behavior to create this 0x80000000-byte slice using `std::slice::from_raw_parts()`. Compiler optimizations can behave erratically if this precondition is violated.

The most straightforward solution would be to add assertions to `MmapOptions::map()`, `MmapOptions::map_exec()`, `MmapOptions::map_mut()`, `MmapOptions::map_copy()`, and `MmapOptions::map_copy_read_only()`, and `MmapOptions::map_anon()` that the provided or computed length is no greater than `isize::MAX`. `MmapOptions::map_raw()` does not need this assertion, since `MmapRaw` does not provide slices in safe code. (It may also be worthwhile to add a method that produces an anonymous `MmapRaw` not checked against `isize::MAX`.)

**Comment by RazrFalcon** [comment]
I guess you're referring to:

>However, some 32-bit and 16-bit platforms may successfully serve a request for more than isize::MAX bytes with things like Physical Address Extension. As such, memory acquired directly from allocators or memory mapped files may be too large to handle with this function.

An assertions would be too sporadic. I guess we should simply return an error and update the docs.

**Comment by RazrFalcon** [comment]
I cannot find how `std::fs::read` handles this. It should handle this exact case.

**Comment by RazrFalcon** [comment]
@adamreichold Hi! Can you comment on this one? It fills like half of the bugs we had are 32-bit related. But disabling its support completely would be too much.

**Comment by LegionMammal978** [comment]
> I cannot find how `std::fs::read` handles this. It should have the exact issue.

Following the call chain, `std::fs::read()`

- [calls](https://doc.rust-lang.org/1.62.0/src/std/fs.rs.html#248) `<File as Read>::read_to_end()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/std/fs.rs.html#654) `Vec::reserve()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/alloc/vec/mod.rs.html#815) `RawVec::reserve()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/alloc/raw_vec.rs.html#289) `RawVec::reserve::do_reserve_and_handle()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/alloc/raw_vec.rs.html#285) `RawVec::grow_amortized()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/alloc/raw_vec.rs.html#400) `alloc::raw_vec::finish_grow()`,
- which [calls](https://doc.rust-lang.org/1.62.0/src/alloc/raw_vec.rs.html#458) `alloc::raw_vec::alloc_guard()`,
- which [checks](https://doc.rust-lang.org/1.62.0/src/alloc/raw_vec.rs.html#505) the size in bytes against `isize::MAX as usize`.

**Comment by RazrFalcon** [comment]
Nice fined. I guess I will borrow this function.

**Comment by adamreichold** [comment]
> @adamreichold Hi! Can you comment on this one? It fills like half of the bugs we had are 32-bit related. But disabling its support completely would be too much.

I think it is a straight-forward error on our side. We do have the necessary check for file-based mappings in `MmapOptions::get_len`, but not in `MmapOptions::len`.

**Comment by adamreichold** [comment]
I think our check in `get_len` was actually too lenient as well. I still think this is a straight-forward bug though, as exposing `mmap (2)`, we are in the memory allocator business need to take the same care as other implementors of such functionality. 😓
