### ISSUE TITLE
How do I do it for seek_mut()?

### ISSUE THREAD

**Issue by rockit-ba** [RazrFalcon/memmap2-rs#65]
like this:
```rust
use memmap2::MmapMut;

let mut mmap = MmapMut::open_path(file_path, memmap2::Protection::ReadWrite)?;
mmap.seek_mut(10)?; 
```

**Comment by adamreichold** [comment]
Is not clear what you mean by `seek_mut`. You also seem to refer to the API of another crate as this crate does have an `open_path` method or a `Protection` enum.

Do you mean how to turn `MmapMut` into an instance of [`Seek`](https://doc.rust-lang.org/stable/std/io/trait.Seek.html)? If so, then the answer to wrap it in a [`Cursor`](https://doc.rust-lang.org/stable/std/io/struct.Cursor.html), e.g.

```rust
let mmap = MmapMut::open(file)?;
let mut cursor = Cursor::new(mmap);
cursor.seek(SeekFrom::Start(10))?; 
```

**Comment by rockit-ba** [comment]
> Is not clear what you mean by `seek_mut`. You also seem to refer to the API of another crate as this crate does have an `open_path` method or a `Protection` enum.
> 
> Do you mean how to turn `MmapMut` into an instance of [`Seek`](https://doc.rust-lang.org/stable/std/io/trait.Seek.html)? If so, then the answer to wrap it in a [`Cursor`](https://doc.rust-lang.org/stable/std/io/struct.Cursor.html), e.g.
> 
> ```rust
> let mmap = MmapMut::open(file)?;
> let mut cursor = Cursor::new(mmap);
> cursor.seek(SeekFrom::Start(10))?; 
> ```

ok thanks
