### ISSUE TITLE
how can t do than is appand?

### ISSUE THREAD

**Issue by rockit-ba** [RazrFalcon/memmap2-rs#66]
```
pub fn write(&mut self, data: &[u8]) {
        let m_mut = &mut self.writer; // this is a &mut MmapMut

        info!("mmap size：{},data size：{}", m_mut.len(), data.len());
        if m_mut.len() > data.len() {
            m_mut.deref_mut().write_all(data).unwrap();
            return;
        }
    }
```
In this way, subsequent writes always overwrite previous writes. I must use a variable to record the size of the previous write and then pass [pre_size..] Is this the way I want to write it?

**Comment by adamreichold** [comment]
The call to `m_mut.deref_mut()` produces a mutable slice `&mut [u8]` covering the whole mapped area each time. This mutable slice [implements `Write`](https://doc.rust-lang.org/stable/std/io/trait.Write.html#impl-Write-for-%26mut%20%5Bu8%5D) by advancing the pointer and adjusting the length.

If you want consecutive calls to your `write` function append data to the end, you will either have to keep the mutable slice around or as you suggest keep your own cursor/position/offset around and do `m_mut.deref_mut()[self.pos..].write_all(data).unwrap();` followed by `self.pos += data.len();`.

**Comment by rockit-ba** [comment]
> The call to `m_mut.deref_mut()` produces a mutable slice `&mut [u8]` covering the whole mapped area each time. This mutable slice [implements `Write`](https://doc.rust-lang.org/stable/std/io/trait.Write.html#impl-Write-for-%26mut%20%5Bu8%5D) by advancing the pointer and adjusting the length.
> 
> If you want consecutive calls to your `write` function append data to the end, you will either have to keep the mutable slice around or as you suggest keep your own cursor/position/offset around and do `m_mut.deref_mut()[self.pos..].write_all(data).unwrap();` followed by `self.pos += data.len();`.
yes,i do that, like ```self.pos += data.len()```，thanks very much
