### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by bzm3r** [RazrFalcon/memmap2-rs#7]
I'm wondering if there's a reason for the fork, and upon what basis I should choose to use memmap v1 versus v2?

**Comment by RazrFalcon** [comment]
1. https://github.com/RazrFalcon/memmap2-rs/blob/master/CHANGELOG.md
2. Original memmap is abandoned.

**Comment by bzm3r** [comment]
@RazrFalcon Thank you! That makes sense.
