### ISSUE TITLE
Alignment issue on Windows with empty file

### ISSUE THREAD

**Issue by timvisee** [RazrFalcon/memmap2-rs#78]
The Windows implementation has a problem when trying to create a mmap for an empty file.

Normally, Windows creates a mmap that is aligned in memory. But there's a catch. An empty file gets a pointer to address 1 (0x00000001), which is not aligned.

In [Qdrant](https://github.com/qdrant/qdrant) this was problematic, because we always expected an aligned mmap. We therefore [handle](https://github.com/qdrant/qdrant/blob/3998345b29f86c1c7cf731d9319637d648faf678/lib/segment/src/common/mmap_type.rs#L452-L457) this edge case, returning a [dangling](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.dangling) pointer that is aligned. This is fine because there's no data at the pointer, the byte slice is empty.

Can I submit a PR to implement a similar fix; return an aligned pointer on Windows? Or is the current behavior desirable, and should I not expect to get an aligned pointer?

---

I'm unsure why this happens on Windows, and couldn't find anything about this in the Windows API documentation. I assume it is an error code, where returning a null pointer is not an option so it picks the next address. This is very easily reproducible however.

This only happens on Windows. Unix-like platforms don't have this problem and return an aligned pointer.

```rust
use memmap2::Mmap;
use std::fs::File;

fn main() {
    let file = File::options()
        .read(true)
        .write(true)
        .create(true)
        .open("./empty-file.txt")
        .unwrap();
    file.set_len(0).unwrap();

    let mmap = unsafe { Mmap::map(&file).unwrap() };

    println!("Mmap pointer: {:?}", mmap.as_ptr());
}
```

```bash
# Windows
$ cargo run
Mmap pointer: 0x000000000001

# Linux, macOS
$ cargo run
Mmap pointer: 0x7f51653c1000
```

Related: https://github.com/qdrant/qdrant/pull/1873
CC: @Jesse-Bakker

**Comment by adamreichold** [comment]
> Can I submit a PR to implement a similar fix; return an aligned pointer on Windows? Or is the current behavior desirable, and should I not expect to get an aligned pointer?

Please do and include the above test case.

Please also have a look at `windows::MmapInner::new` which already seems to try to handle this situation but apparently does not do it correctly. I suspect it should check `len` instead of `aligned_len`?

**Comment by adamreichold** [comment]
This was originally introduced in https://github.com/RazrFalcon/memmap2-rs/commit/118344980efaaff161c68921a604fee110a84919 and I think the check was indeed incorrect from the beginning.

**Comment by timvisee** [comment]
I think you're right. Good to see documentation linked there.

I'll submit a PR.

**Comment by timvisee** [comment]
On second look, it is not the Windows API that returns (0x00000001), but the `empty_slice_ptr()` function:

```rust
fn empty_slice_ptr() -> *mut c_void {
    std::ptr::NonNull::<u8>::dangling().cast().as_ptr()
}
```

`u8` is a single byte, the first aligned address after null is (0x00000001).

**Comment by timvisee** [comment]
What about something like this (untested)?

```rust
fn empty_slice_ptr() -> *mut c_void {
    let align = allocation_granularity().max(1);
    let ptr = unsafe { std::ptr::null_mut::<u8>().add(align) };
    ptr
}
```

**Comment by Jesse-Bakker** [comment]
```rust
allocation_granularity as *mut c_void
```
should do it (provided allocation_granularity is not 0)

**Comment by timvisee** [comment]
> should do it (provided allocation_granularity is not 0)

I'm unsure if that is guaranteed.

**Comment by adamreichold** [comment]
I think for future compatibility with strict provenance we should use `transmute` instead of `as *mut c_void`, c.f. https://doc.rust-lang.org/stable/src/core/ptr/mod.rs.html#593

**Comment by timvisee** [comment]
Thanks a lot for being so responsive allowing to resolve this so quickly! :smile:
