### ISSUE TITLE
Mac osx support

### ISSUE THREAD

**Issue by ssh352** [RazrFalcon/memmap2-rs#80]
it is not mentioned in the repo but cargo build and test run ok on osx. 

So is OSX officially supported without issues?

**Comment by RazrFalcon** [comment]
Yes.

>A list of supported/tested targets can be found in [Actions](https://github.com/RazrFalcon/memmap2-rs/actions).

https://github.com/RazrFalcon/memmap2-rs/actions/runs/5069529932 (see the left panel)
