### ISSUE TITLE
Mapping beyond 4GB offset if broken on 32 bit glibc (Linux)

### ISSUE THREAD

**Issue by lvella** [RazrFalcon/memmap2-rs#85]
This is a direct consequence of this [rust's libc issue](https://github.com/rust-lang/libc/issues/3223). In rust targeting 32 bits glibc, `libc::off_t` is 32 bits, which breaks [this code](https://github.com/RazrFalcon/memmap2-rs/blob/04178aa13f1ffa07536a0a11280e454ecde3d19a/src/unix.rs#L59) if you are trying to map beyond 4 GB in a file:
```
            let ptr = libc::mmap(
                ptr::null_mut(),
                map_len as libc::size_t,
                prot,
                flags,
                file,
                aligned_offset as libc::off_t,
            );
```

I had a similar issue with `nix` crate, where `posix_fallocate()` also relied on `libc::off_t` for file sizes. The fix was to use `rustix` crate, that calls the system-call directly. Maybe a similar workaround could be applied here?

**Comment by RazrFalcon** [comment]
Switching to `rustix` seems like a pretty extreme solution. Will wait for `libc` fix.

**Comment by lvella** [comment]
Then I suggest at least doing `aligned_offset.try_into().unwrap()` instead of `aligned_offset as libc::off_t`, or an assert like `assert!(aligned_offset <= libc::off_t::MAX);`. That would have saved me a lot of debugging time.

**Comment by RazrFalcon** [comment]
Feel free to send a pull request.
