### ISSUE TITLE
Interest is supporting mbind

### ISSUE THREAD

**Issue by ollie-etl** [RazrFalcon/memmap2-rs#99]
The api currently allows us to `madvise` memory maps. Would there be an interest in also providing an [mbind](https://man7.org/linux/man-pages/man2/mbind.2.html) functionality?

**Comment by RazrFalcon** [comment]
If someone is willing to implement it - sure.

**Comment by adamreichold** [comment]
> The headache is either upstreaming the mbind call to libc, or using syscall here directly

I think as a third option, you could also just put the prototype of the libc function into this crate until the upstreaming is complete. (We do use the same approach for the Windows API calls used here for example.)

**Comment by ollie-etl** [comment]
There is no libc function for mbind, it involves either using `libnuma`, or calling `syscall` directly, with the appropriate op. As that's all libnuma does, i think the latter is preferable.

**Comment by RazrFalcon** [comment]
Then I guess this is out of scope.

**Comment by ollie-etl** [comment]
How do you feel about a dependency on the syscalls crate?

**Comment by RazrFalcon** [comment]
It's way out of scope. This crate is for memory mapping only.

**Comment by ollie-etl** [comment]
its exactly the same rational as `mlock` and `madvise`, both of which have apis: you'd like to control some aspect of the mapping, in this can its allocation onto a specific numa node.

**Comment by RazrFalcon** [comment]
`madvice` is in libc. And it already caused too many problems. I'm not interested in maintaining more features.

**Comment by ollie-etl** [comment]
understood. Closing this issue.
